[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "mkdocs serve -a 0.0.0.0:$PORT"
